### ISSUE TITLE
why not to use 'callable' to expand vars

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_runner#5]
```
>>> callable(os.path.isfile)
True
```

**Comment by halfbrained** [comment]
[this?](https://github.com/halfbrained/cuda_runner/commit/d78b4efe0c0a7633c1060ef0f4f1c0fa25e787af#diff-34cde5e49b54d9b67952c80d3580b6c421ebcf16097996e215aef54e44f78562R688-R691)

Because most of the results will be callables - [justification :) ](https://docs.python.org/3.9/glossary.html#term-eafp) ... should I change it?

**Comment by Alexey-T** [comment]
yes, that place. feel free to leave as is
